### ISSUE TITLE
Back-end setup

### ISSUE THREAD

**Issue by OmidKhodaparast2002** [tehreemAsif63/DigitalTwins#4]
## User Story

**As a** doctor,  
**I want** the system to have a working back-end,  
**so that** so that I can use it to send patient data to the front-end for visualisation.

## Acceptance Criteria

- [x] The back-end shall make use of the `Express` framework to handle HTTP requests
- [x] The back-end shall have `typescript` as part of the dependencies allowing developers to use types to make the code readable and understandable
- [x] The back-end shall have `nodemon` and `morgan` packages installed. `nodemon` allows the back-end to restart running upon changes made to the code. `morgan` logs incoming HTTP requests to the console.
- [x] The back-end shall have general route `/api/v1`. When a request is sent to this route, the message `Welcome to Codeiologist` shall be sent to the front-end
- [x] The back-end shall run on port 5000 or use the port number saved on the environment variable called `PORT`.
- [x] The back-end shall handle requests sent to routes that do not exist and respond with status code `404`and the message `Not found.`
- [x] The back-end shall use HTTPS 
- [x] The back-end setup shall be modular to facilitate later development and maintenance.

**Comment by OmidKhodaparast2002** [comment]
Some of them are already done in the project setup that we did yesterday. Some are partly done and need some changes. I have checked the acc criteria that are done. Please @ me if there are any ambiguities, or ask in the discord channel.

**Comment by YingchaoJiStone** [comment]
I added another acceptance criteria (The back-end setup shall be modular to facilitate later development and maintenance) to the issue description.
